server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
      routes:
        - id: ms-listas-espera
          uri: lb://MS-LISTAS-ESPERA
          predicates:
            - Path=/api/listas-espera/**
        
        - id: ms-portal-paciente
          uri: lb://MS-PORTAL-PACIENTE
          predicates:
            - Path=/api/portal-paciente/**
        
        - id: ms-reasignacion
          uri: lb://MS-REASIGNACION
          predicates:
            - Path=/api/reasignacion/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka/}

# Configuración JWT
jwt:
  secret: RedNorte2026SecretKeyForJwtTokenGenerationAndValidation!@#
  expiration: 3600000
