<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.rednorte.archetypes</groupId>
  <artifactId>rednorte-ms-archetype</artifactId>
  <version>1.0.0</version>
  <packaging>maven-archetype</packaging>

  <name>rednorte-ms-archetype</name>
  <description>Arquetipo Maven base reutilizable (no runtime) para la generacion automatica de microservicios y BFFs en la Plataforma RedNorte.</description>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>21</maven.compiler.source>
    <maven.compiler.target>21</maven.compiler.target>
  </properties>

  <build>
    <extensions>
      <extension>
        <groupId>org.apache.maven.archetype</groupId>
        <artifactId>archetype-packaging</artifactId>
        <version>3.2.1</version>
      </extension>
    </extensions>

    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-archetype-plugin</artifactId>
          <version>3.2.1</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-resources-plugin</artifactId>
          <version>3.3.1</version>
          <configuration>
            <addDefaultDelimiters>false</addDefaultDelimiters>
            <useDefaultDelimiters>false</useDefaultDelimiters>
            <delimiters>
              <delimiter>__*__</delimiter>
            </delimiters>
          </configuration>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>
</project>
